services:
  fcgi:
    build: .
    deploy:
      replicas: 3
    networks:
      - backend

  nginx:
    image: nginx
    depends_on:
      - fcgi
    ports:
      - "1801:1801"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./static:/var/www"
    networks:
      - backend

networks:
  backend:
    driver: bridge