services:
  fcgi:
    build: .
    deploy:
      replicas: 3
    networks:
      - backend

  nginx:
    image: nginx
    depends_on:
      - fcgi
    ports:
      - "1801:1801"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./static:/var/www"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1801/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - backend


  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - mongo-data:/data/db

    networks:
      - backend
volumes:
  mongo-data:

networks:
  backend:
    driver: bridge