Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.network "forwarded_port", guest: 1801, host: 1801
  config.vm.network "forwarded_port", guest: 27017, host: 27017


  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provision "shell", path: "scripts/provision.sh"

  config.vm.provision "shell", inline: <<-SHELL
    cd /vagrant
    docker swarm init
    docker stack deploy -c docker-compose.yml my-stack
  SHELL
end